<style>
.store-inventory-table 
{
    width: 100%;    
    margin: 10px;
    border: 1px solid black;
}
tr.store-inventory-row {
    border: 1px solid black;
}
tr.store-inventory-row >th {
    border: 1px solid black;
}
tr.store-inventory-row >td {
    border: 1px solid black;
}
#addstoreinventory
{
    margin: 25px;
}
tr.store-inventory-row >td > select
{
    width:100%;
    padding:3px;
    margin: 0;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
    border-radius:4px;
    -webkit-box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
    -moz-box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
    box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
   
    color:#888;
    border:none;
    outline:none;
    display: inline-block;
    -webkit-appearance:none;
    -moz-appearance:none;
    appearance:none;
    cursor:pointer;
}
</style>
<?php
    $storeDetails=$block->getStoreDetails();
    $storeInventoryDetails=$block->getStoreInventoryDetails();    
    $storeInventoryDetails_count=count($storeInventoryDetails);
?>
<input id="existinginventorycount" name="product[existinginventorycount]" type="hidden" value="<?php echo $storeInventoryDetails_count;?>"/>
<script>
    jQuery( document ).ready(function() {
        function deletestoreinventoryrow(rowid)
        {
            var idname='store_inventory_row_'+rowid;
            jQuery("#"+idname).remove();
        }
        jQuery("#addstoreinventory").click(function(e)
        {            
            var existinginventorycount=parseInt(jQuery("#existinginventorycount").val());
            var store_inventory_row='<tr id="store_inventory_row_'+existinginventorycount+'" class="store-inventory-row"><td>';
            store_inventory_row+='<select class=" input-text admin__control-text store_id required-entry" name="product[storeinventory]['+existinginventorycount+'][store_id]" id="storeinventory_row_'+existinginventorycount+'_store_id">';
            store_inventory_row+='<option value="">-- Select --</option>';
            <?php
                if(count($storeDetails)>0)
                {
                    foreach($storeDetails as $sd)
                    {
                        ?>
                        store_inventory_row+='<option value="<?php echo $sd['id']; ?>"><?php echo $sd['name']; ?></option>';
                        
                        <?php
                    }
                }
            ?>
            
            store_inventory_row+='</select></td>';    
            store_inventory_row+="<td>";
            store_inventory_row+='<input class=" input-text admin__control-text qty required-entry validate-greater-than-zero" type="text" name="product[storeinventory]['+existinginventorycount+'][qty]" value="0" id="storeinventory_row_'+existinginventorycount+'_qty">';
            store_inventory_row+="</td>";
            store_inventory_row+='<td><button onclick="jQuery('+"'#store_inventory_row_"+existinginventorycount+"'"+').remove();;" class="deletestoreinventory" title="Delete Inventory" type="button" class="action-default scalable add"  data-ui-id="widget-button-4"><span>Delete</span></button>';
            store_inventory_row+="</td></tr>";
            jQuery(".store-inventory-row.addstoreinventory").before(store_inventory_row);
            existinginventorycount+=1;
            jQuery("#existinginventorycount").val(existinginventorycount);
        });
        
    });
</script>
<table class="store-inventory-table admin__control-table ">
    <tr class="store-inventory-row"><th>Store</th><th>Inventory</th><th>Action</th></tr>
    <?php
        if($storeInventoryDetails_count>0)
        {
            $output="";
            $i=0;
            foreach($storeInventoryDetails as $storeInventoryData)
            {
                $output.='<tr id="store_inventory_row_'.$i.'" class="store-inventory-row">';
                $output.='<td>';
                $output.='<select class=" input-text admin__control-text store_id required-entry" name="product[storeinventory]['.$i.'][store_id]" id="storeinventory_row_'.$i.'_store_id">';
                $output.='<option value="">-- Select --</option>';               
                if(count($storeDetails)>0)
                {
                    foreach($storeDetails as $sd)
                    {
                        $sel="";
                        if($storeInventoryData['storepickup_store_id']==$sd['id'])
                        {
                            $sel=" selected ";
                        }
                        $output.='<option value="'.$sd['id'].'" '.$sel.' >'.$sd['name'].'</option>';                        
                    }
                }              
                $output.='</select></td>';                
                $output.='<td><input class=" input-text admin__control-text qty required-entry validate-greater-than-zero" type="text" name="product[storeinventory]['.$i.'][qty]" value="'.$storeInventoryData['qty'].'" id="storeinventory_row_'.$i.'_qty"></td>';
                $output.='<td><button onclick="jQuery('."'#store_inventory_row_".$i."'".').remove();;" class="deletestoreinventory" title="Delete Inventory" type="button" class="action-default scalable add"  data-ui-id="widget-button-4"><span>Delete</span></button></td>';
                $output.="</tr>";
                $i++;
            }
            echo $output;
        }
    ?>
    <tr class="store-inventory-row addstoreinventory"><td colspan="3"><button id="addstoreinventory" title="Add Inventory" type="button" class="action-default scalable add"  data-ui-id="widget-button-4">
    <span>Add Inventory</span>
</button></td></tr>
</table>
