<li class="quickorderlink">
    <span class="" role="link" tabindex="0" data-toggle="dropdown" data-trigger-keypress-button="true" data-bind="scope: 'customer'" aria-haspopup="true" aria-expanded="true">
        <span >Quick Order</span>            
    </span>

    <div class="QuickOrderMenu" data-target="dropdown" aria-hidden="false">
        <div class="block block-minicart empty ui-dialog-content ui-widget-content" data-role="dropdownDialog" id="ui-id-1" style="display: block;">
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() -->
<div class="block-title">
    <strong>
        <span class="text"><!-- ko i18n: 'My Cart' --><span>My Cart</span><!-- /ko --></span>
        <span class="qty" data-bind="css: { empty: cart().summary_count == 0 },
                       attr: { title: $t('Items in Cart') }" title="Items in Cart">
            <!-- ko text: cart().summary_count -->1<!-- /ko -->
        </span>
    </strong>
</div>

<div class="block-content">
    <button type="button" id="btn-minicart-close" class="action close" data-action="close" data-bind="attr: { title: $t('Close') }" title="Close">
        <span><!-- ko i18n: 'Close' --><span>Close</span><!-- /ko --></span>
    </button>

    <!-- ko if: cart().summary_count -->
        <div class="items-total">
            <span class="count"><!-- ko text: cart().summary_count -->1<!-- /ko --></span>
            <!-- ko if: cart().summary_count == 1 -->
                <!-- ko i18n: 'item' --><span>item</span><!-- /ko -->
            <!-- /ko -->
            <!-- ko if: cart().summary_count > 1 --><!-- /ko -->
        </div>

        <!-- ko if: cart().possible_onepage_checkout -->
            <!-- ko foreach: getRegion('subtotalContainer') -->
                <!-- ko template: getTemplate() -->
<!-- ko foreach: { data: elems, as: 'element' } -->
    <!-- ko if: hasTemplate() -->
        <!-- ko template: getTemplate() -->
<div class="subtotal">
    <span class="label">
        <!-- ko i18n: 'Cart Subtotal' --><span>Cart Subtotal</span><!-- /ko -->
    </span>

    <!-- ko foreach: elems -->
        <!-- ko template: getTemplate() -->

<div class="amount price-container">
    <!-- ko if: displaySubtotal() -->
        <!-- ko if: display_cart_subtotal_excl_tax -->
            <span class="price-wrapper" data-bind="html: cart().subtotal_excl_tax"><span class="price">$59.00</span></span>
        <!-- /ko -->

        <!-- ko if: !display_cart_subtotal_excl_tax && display_subtotal_incl_tax --><!-- /ko -->

        <!-- ko if: !display_cart_subtotal_excl_tax && !display_subtotal_incl_tax --><!-- /ko -->
    <!-- /ko -->
    <!-- ko ifnot: displaySubtotal() --><!-- /ko -->
</div>
<!-- /ko -->
    <!-- /ko -->
</div>
<!-- /ko -->
    <!-- /ko -->
<!-- /ko -->
<!-- /ko -->
            <!-- /ko -->
        <!-- /ko -->

        <!-- ko foreach: getRegion('extraInfo') -->
            <!-- ko template: getTemplate() -->
<!-- ko foreach: { data: elems, as: 'element' } --><!-- /ko -->
<!-- /ko -->
        <!-- /ko -->

        <!-- ko if: cart().possible_onepage_checkout -->
        <div class="actions">
            <div class="primary">
                <button id="top-cart-btn-checkout" type="button" class="action primary checkout" data-bind="attr: {title: $t('Go to Checkout')}" title="Go to Checkout">
                    <!-- ko i18n: 'Go to Checkout' --><span>Go to Checkout</span><!-- /ko -->
                </button>
                <div data-bind="html: cart().extra_actions"></div>
            </div>
        </div>
        <!-- /ko -->
    <!-- /ko -->

    <!-- ko if: cart().summary_count -->
    <strong class="subtitle"><!-- ko i18n: 'Recently added item(s)' --><span>Recently added item(s)</span><!-- /ko --></strong>
    <div data-action="scroll" class="minicart-items-wrapper overflowed">
        <ol id="mini-cart" class="minicart-items" data-bind="foreach: { data: cart().items, as: 'item' }" style="height: 110px;">
            <!-- ko foreach: $parent.getRegion($parent.getItemRenderer(item.product_type)) -->
                <!-- ko template: {name: getTemplate(), data: item, afterRender: function() {$parents[1].initSidebar()}} -->
<li class="item product product-item" data-role="product-item">
    <div class="product">
        <!-- ko if: product_has_url -->
        <a data-bind="attr: {href: product_url, title: product_name}" tabindex="-1" class="product-item-photo" href="http://localhost/magento/fusion-backpack.html" title="Fusion Backpack">
            <!-- ko foreach: $parent.getRegion('itemImage') -->
                <!-- ko template: {name: getTemplate(), data: item.product_image} -->
<span class="product-image-container" data-bind="style: {width: width + 'px'}" style="width: 75px;">
    <span class="product-image-wrapper" data-bind="style: {'padding-bottom': height/width*100 + '%'}" style="padding-bottom: 100%;">
        <img class="product-image-photo" data-bind="attr: {src: src, alt: alt}, style: {width: width + 'px', height: height + 'px'}" src="http://localhost/magento/pub/media/catalog/product/cache/1/thumbnail/75x75/beff4985b56e3afdbeabfc89641a4582/m/b/mb02-gray-0.jpg" alt="Fusion Backpack" style="width: 75px; height: 75px;">
    </span>
</span>
<!-- /ko -->
            <!-- /ko -->
        </a>
        <!-- /ko -->
        <!-- ko ifnot: product_has_url --><!-- /ko -->

        <div class="product-item-details">
            <strong class="product-item-name">
                <!-- ko if: product_has_url -->
                <a data-bind="attr: {href: product_url}, text: product_name" href="http://localhost/magento/fusion-backpack.html">Fusion Backpack</a>
                <!-- /ko -->
                <!-- ko ifnot: product_has_url --><!-- /ko -->
            </strong>

            <!-- ko if: options.length --><!-- /ko -->

            <div class="product-item-pricing">
                <!-- ko if: canApplyMsrp --><!-- /ko -->
                <!-- ko ifnot: canApplyMsrp -->
                <!-- ko foreach: $parent.getRegion('priceSidebar') -->
                    <!-- ko template: {name: getTemplate(), data: item.product_price, as: 'price'} -->
<div class="price-container">
  <span class="price-wrapper" data-bind="html: price">

    <span class="price-excluding-tax" data-label="Excl. Tax">
            <span class="minicart-price">
            <span class="price">$59.00</span>        </span>

        </span>
</span>
</div>


                <div class="details-qty qty">
                    <label class="label" data-bind="i18n: 'Qty', attr: {
                           for: 'cart-item-'+item_id+'-qty'}" for="cart-item-7-qty">Qty</label>
                    <input data-bind="attr: {
                           id: 'cart-item-'+item_id+'-qty',
                           'data-cart-item': item_id,
                           'data-item-qty': qty
                           }, value: qty" type="number" size="4" class="item-qty cart-item-qty" maxlength="12" id="cart-item-7-qty" data-cart-item="7" data-item-qty="1">
                    <button data-bind="attr: {
                           id: 'update-cart-item-'+item_id,
                           'data-cart-item': item_id,
                           title: $t('Update')
                           }" class="update-cart-item" style="display: none" id="update-cart-item-7" data-cart-item="7" title="Update">
                        <span data-bind="i18n: 'Update'">Update</span>
                    </button>
                </div>
            </div>

            <div class="product actions">
               
                
                <div class="primary">
                    <a data-bind="attr: {href: configure_url, title: $t('Edit item')}" class="action edit" href="http://localhost/magento/checkout/cart/configure/id/7/product_id/6/" title="Edit item">
                        <span data-bind="i18n: 'Edit'">Edit</span>
                    </a>
                </div>
                <!-- /ko -->
                <div class="secondary">
                    <a href="#" data-bind="attr: {'data-cart-item': item_id, title: $t('Remove item')}" class="action delete" data-cart-item="7" title="Remove item">
                        <span data-bind="i18n: 'Remove'">Remove</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</li>

        </ol>
    </div>

    <div class="actions">
        <div class="secondary">
            <a class="action viewcart" data-bind="attr: {href: shoppingCartUrl}" href="http://localhost/magento/checkout/cart/">
                <span><!-- ko i18n: 'View and edit cart' --><span>View and edit cart</span><!-- /ko --></span>
            </a>
        </div>
    </div>
  
    <div id="minicart-widgets" class="minicart-widgets">
   
    </div>
</div>

            </div>
        </div>
    </div>
</li>