<style>
    .rameshscrolltop_div
    {
        position: fixed;
        bottom: 30px;
        right: 30px;
        width: 35px;
        height: 35px;
        border-radius: 14px 14px 14px 14px;
        background: #040D17;
        color: white;
        text-align: center;
        align-content: center;
        padding-top: 6px;
        font-weight: 700;
        z-index: 9999;
        display:none;
    }
</style>
<script type="text/javascript">
require(['jquery'],function($){
    $(window).scroll(function () {
       
        $("#current_window_top").val($(this).scrollTop());
        
        if ($(this).scrollTop() != 0) {
            $(".rameshscrolltop_div").show("fast");
        } else {
            $(".rameshscrolltop_div").hide(1000);
        }
    });

    $(".rameshscrolltop_div").click(function () {
        var top = 0;
        if ($("#current_window_top").length > 0)
        {
            top =0;
            
        }
        $("body,html").animate({scrollTop: top}, 800);
    });
    
});
</script>
<div class="rameshscrolltop_div">
    <input type="hidden" name="current_window_top" id="current_window_top" value="" />
    <span>Top</span>
</div>